<b>Recursive Changes

In [40]:
%%html
<img src="img/recursive-calls.png",width = 400, height = 400>

In [40]:
import math as m
def RecursiveChanges(money, coins):     #money: single value   #coins: array of denominator values available
    if money == 0 :
        return 0
    minimum_number_coins = m.inf
    count = 0;
    for coin in coins:                 #for each coin in [coin1, coin2, coin3...]
        if coin <= money:
            Number_of_coins = RecursiveChanges(money-coin, coins)
        if Number_of_coins < minimum_number_coins:
            minimum_number_coins = Number_of_coins + 1
    return minimum_number_coins

In [41]:
RecursiveChanges(17,[1,4,5])

4

In [42]:
## Generate an array for m = 1 - 12
max_money = 22; minimum_coins = []; coins = [1,4,5]
for money in range(13,max_money+1):
    minimum_coins.append(RecursiveChanges(money,coins))
print(' '.join(str(i) for i in minimum_coins))

3 3 3 4 4 4 4 4 5 5


<b>Dynamic Programming 

In [75]:
import math as m
def DP_Changes(money,coins):        #money: single value   #coins: array of denominator values available
    minimum_coins = []
    minimum_coins.insert(0,0)
    for mon in range(money):
        minimum_coins.append(m.inf)
        for coin in coins:
            if mon >= coin:           # don't bother if the coin value is larger than money (you cannot get integer)
                last_minimum_coin = minimum_coins[mon-coin]    # recall previous minimum coin for (m-coin)
                if last_minimum_coin + 1 < minimum_coins[mon]:
                    minimum_coins[mon] = last_minimum_coin + 1
    return minimum_coins[mon]

In [72]:
file = open('CC1-change_problem.txt','r')
data = file.read(); data
money, coins, _ = data.split('\n'); money = int(money); coins = [int(i) for i in coins.split(',')]
print(money); print(coins)
file.close()

19281
[6, 5, 3, 1]


In [73]:
minimum_coin_array = DP_Changes(money, coins)
print(minimum_coin_array)

3214


<b>Manhattan Tourist Problem

In [196]:
import numpy as np
def ManhattanTourist(row, col, down_matrix, right_matrix,diag_matrix): #If 4x4 grid | down matrix: 4x5 | right matrix: 5 x 4
    node_matrix = np.zeros((row+1,col+1))    
    for i in range(0,row):   # calculate first column #row: 4 #reiterate 4 times
        node_matrix[i+1][0] = node_matrix[i][0] + down_matrix[i][0]    #down_matrix 4x5
    for j in range(0, col):  # calculate first column #col: 4 #reiterate 4 times
        node_matrix[0][j+1] = node_matrix[0][j] + right_matrix[0][j]   #right_matrix 5x4
    
    for i in range(1,row+1):   # Start calculating (1,1),(1,2)....(1,5)
        for j in range(1,col+1):
            node2node_down = node_matrix[i-1][j] + down_matrix[i-1][j]; 
            node2node_right = node_matrix[i][j-1] + right_matrix[i][j-1];
            node_matrix[i][j] = max(node2node_down,node2node_right)      #get max node value
            if diag_matrix != '':    ## diagonal option
                node_matrix[i][j] = max(node_matrix[i][j],node_matrix[i-1][j-1]+ diag_matrix[i-1][j-1])
            #print(node_matrix)
    return node_matrix[-1][-1]

In [11]:
file = open('CC2-Manhattan_tourist.txt','r')
data = file.read(); data = data.split('\n')
row, col = data[0].split(' '); row = int(row); col = int(col); 
down_matrix_data = data[1:row+1]; down_matrix_data =  [i.split(' ') for i in down_matrix_data]
right_matrix_data = data[row+2:-1]; right_matrix_data = [i.split(' ') for i in right_matrix_data]
file.close()
print(row); print(col);

5
14


In [198]:
down_matrix = np.array([[int(item) for item  in row] for row in down_matrix_data])
right_matrix = np.array([[int(item) for item in row] for row in right_matrix_data])
print(down_matrix); 

[[4 1 4 3 1 4 0 1 2 4 3 0 0 3 3]
 [3 4 4 4 0 1 2 1 0 2 1 1 1 0 1]
 [3 1 2 1 1 4 3 1 0 0 3 1 4 3 1]
 [4 3 1 2 2 3 1 1 4 3 0 3 2 1 3]
 [0 0 2 4 1 4 4 0 4 2 2 0 1 0 1]]


In [199]:
ManhattanTourist(row,col, down_matrix, right_matrix,_)

52.0

<b>Matrix Backtracking

In [726]:
# Denote "down", "right","diagonal" (match) = -1, 0, 1     Dummy Variables
def LCS_Backtrack(string1, string2): #If 4x4 grid       string1: vertical    string2: horizontal
    k1 = len(string1); k2 = len(string2);
    node_matrix = np.zeros((k1+1 ,k2+1))    # assigned a 2D zero matrix for node value 5x5  
    backtrack_matrix = np.zeros((k1,k2))      # backtrack pointers
    for i in range(1,k1+1):   # Start calculating (1,1),(1,2)....(1,5)
        for j in range(1,k2+1):
#Form Node Matrix with Max Value
            if string1[i-1] == string2[j-1]:
                match = 1
            else:
                match = 0
            node_matrix[i][j] = max(node_matrix[i-1][j],node_matrix[i][j-1], node_matrix[i-1][j-1] + match)
# Get pointer from value comparison
            if node_matrix[i][j] == node_matrix[i-1][j]:      #Go DOWN
                backtrack_matrix[i-1][j-1] = -1
            elif node_matrix[i][j] == node_matrix[i][j-1]:    #Go LEFT
                backtrack_matrix[i-1][j-1] = 0            
            elif node_matrix[i][j] == node_matrix[i-1][j-1] + 1  :  #Go Diagonal
                backtrack_matrix[i-1][j-1] = 1
    print('node matrix\n' + str(node_matrix))
    return backtrack_matrix

In [727]:
backtrack_matrix = LCS_Backtrack('AACCTTGG','ACACTGTGA'); 
backtrack_matrix

node matrix
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 4. 4. 4. 4. 4.]
 [0. 1. 2. 2. 3. 4. 4. 5. 5. 5.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]]


array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1.,  1.,  0.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1.,  1.,  0.,  0.],
       [-1., -1., -1., -1., -1.,  1., -1.,  1.,  0.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1.]])

In [747]:
## Uses While Loop
def LCS_1(v,w):
    backtrack_matrix = LCS_Backtrack(v,w); print('Backtrack Matrix: \n'+str(backtrack_matrix))
    i = len(v)-1; j = len(w)-1; string1 = ''; string2 = ''; LCS_array = []
    while i >= 0 or j >= 0:
        '''
        print('(i,j)= ('+ str(i)+ ', ' + str(j)+')' )
        print('Pointer: ' + str(backtrack_matrix[i][j]))
        ''' 
        if backtrack_matrix[i][j] == -1:  ## Down Pointer, go Up
            i = i - 1
            #string2 = '-' + string2; string1 = v[i+1] + string1
        elif backtrack_matrix[i][j] == 0 :    ## Right pointer, go LEFT
            j = j - 1
            #string1 = '-' + string1; string2 = w[j+1] + string2
        elif backtrack_matrix[i][j] == 1:    ## Down pointer, go UP
            #string1 = v[i+1] + string1; string2 = w[i+1] + string2
            LCS_array.insert(0,v[i])
            i = i - 1; j = j - 1;
    return ''.join(LCS_array)    #string1, string2

## Recursive form
def LCS_2(backtrack_matrix, v, i, j):     # i = len(i); j = len(j)
    if i==0 or j==0:
        return
    backtrack_matrix = LCS_Backtrack(v,w); #print(backtrack_matrix)
    if backtrack_matrix[i][j] == -1:    # Down pointer, go up
        LCS_2(backtrack_matrix, v, i-1, j)
    elif backtrack_matrix[i][j] == 0:    # Right pointer, go left
        LCS_2(backtrack_matrix, v, i, j-1)
    else :    #backtrack_matrix[i][j] == 1
        LCS_2(backtrack_matrix, v, i-1, j-1)
        print(v[i])

In [748]:
v = 'AACCTTGG'; w = 'ACACTGTGA'
LCS_1(v,w)

node matrix
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 4. 4. 4. 4. 4.]
 [0. 1. 2. 2. 3. 4. 4. 5. 5. 5.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]]
Backtrack Matrix: 
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.  0.  0.  0.  0.]
 [-1.  1. -1.  1.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  1.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  1.  0.  0.]
 [-1. -1. -1. -1. -1.  1. -1.  1.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]]


'AACTTG'

In [752]:
file = open('CC3-longest_common_subsequence.txt','r')
data = file.read(); data = data.split('\n'); file.close()
v,w,_ = data; #print(v); print(w)

In [751]:
LCS = LCS_1(v,w)
path_length = len(LCS); print(LCS); print(path_length)

node matrix
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   1.   1. ...   1.   1.   1.]
 [  0.   1.   1. ...   2.   2.   2.]
 ...
 [  0.   1.   2. ... 569. 570. 571.]
 [  0.   1.   2. ... 569. 570. 571.]
 [  0.   1.   2. ... 569. 570. 571.]]
Backtrack Matrix: 
[[ 1.  0.  0. ...  0.  0.  0.]
 [-1. -1. -1. ...  0.  0.  0.]
 [-1. -1. -1. ...  0.  0.  0.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]
TCCTTCCTCTAGGCATGGGCTGCCGCTCCCGACTCCGGGGTGTAGGATAACATGTACTGTGTCCAAGCACGGCACTTCTGAGCCAGCTCTGTGCTTCGCCCATCAGAAATGCTCAGGCCAGTCCAGTCTCCGGAGAAATGCGACGTGGGGCACTGCCCGAGGACCAGAGCTGCTGCCCCCCGTGGGTAGGTAGATACCCGTTATTCGTTCGGTCAGCACATTTAAGACGTGAGAAACCCAGAGCGAGGAGTGATACATTGCCCGCAAAATTTACAAAAGCTTCCCCCCAACTGCACGGAGCGTGACCCGACCAGTACAGTAGAAGGAAGTTAAGAGCGTGAGCTTCGCAGGTTAGCTTTGCAGCCGCGCAAAATTGATGGGCAGGTTGTACATCGACGCGGGTATAGATTTTCTCCGCTGGTGGCCATTTCGGTTTACGCCCTCGCATTACGACTAAATAGCTAAGCCGCTGTGAGGGTTTTTTCCAATAAGTTACTTAAGAATTTCGGGCTTGTATGCCGAATCTTGGCGCCGCGATTGCATTCAGGG

<b> Longest Path In DAG

In [3]:
import numpy as np, math as m
file = open('CC4-longest_path_in_DAG.txt','r')
data = file.read(); data = data.split('\n'); 
start, end, node_weights = data[0], data[1], data[2:-1]; file.close(); start = int(start); end = int(end)
print(node_weights); print(start); print(end)
## Turn data into start points, end point, weights
node_weights = [node_weight.split(':') for node_weight in node_weights]; 
nodes_ = [x.split('->') for x,y in node_weights]; weight_array = [int(y) for x,y in node_weights]; 
start_array = [int(start) for start,end in nodes_]; end_array = [int(end) for start,end in nodes_];

['6->26:32', '10->39:30', '26->28:24', '3->16:19', '10->35:35', '10->37:19', '10->31:36', '10->33:32', '10->32:4', '15->23:0', '15->21:0', '22->24:0', '22->27:31', '1->3:36', '5->43:37', '8->30:23', '19->34:11', '12->13:38', '39->40:35', '12->15:29', '27->29:13', '1->42:31', '24->25:2', '1->10:4', '4->30:11', '13->35:17', '24->28:2', '23->25:37', '31->43:7', '31->40:17', '3->28:2', '5->12:39', '5->11:37', '3->4:4', '2->31:23', '14->29:13', '19->27:21', '27->36:20', '31->33:23', '30->40:27', '28->42:29', '21->35:33', '21->37:5', '20->37:24', '2->9:38', '0->14:19', '4->20:0', '1->41:8', '8->14:28', '19->20:13', '4->43:3', '14->31:25', '14->30:22', '13->41:19', '13->40:32', '14->35:10', '10->11:5', '14->38:23', '2->23:9', '2->25:1', '24->40:37', '12->38:38', '20->23:34', '20->21:29', '12->30:10', '12->37:12', '29->44:30', '33->35:15', '33->37:22', '0->36:8', '37->38:17', '10->29:13', '17->44:11', '6->14:5', '10->22:8', '22->37:19', '22->34:3', '32->43:4', '15->36:28', '11->35:20', '2->16:

In [4]:
from collections import defaultdict
from itertools import chain
def Node2Dict(start_array, end_array, weight_array):     # turn information into dictionary with all information 
    graph = defaultdict(list)
    for start, end, weight in zip(start_array,end_array, weight_array):
        graph[start].append((end,weight))
    return graph

In [5]:
graph = Node2Dict(start_array, end_array, weight_array)
print(graph.keys()); print(graph.values())

dict_keys([6, 10, 26, 3, 15, 22, 1, 5, 8, 19, 12, 39, 27, 24, 4, 13, 23, 31, 2, 14, 30, 28, 21, 20, 0, 29, 33, 37, 17, 32, 11, 7, 16])
dict_values([[(26, 32), (14, 5)], [(39, 30), (35, 35), (37, 19), (31, 36), (33, 32), (32, 4), (11, 5), (29, 13), (22, 8)], [(28, 24)], [(16, 19), (28, 2), (4, 4)], [(23, 0), (21, 0), (36, 28), (30, 25)], [(24, 0), (27, 31), (37, 19), (34, 3), (35, 37)], [(3, 36), (42, 31), (10, 4), (41, 8)], [(43, 37), (12, 39), (11, 37)], [(30, 23), (14, 28)], [(34, 11), (27, 21), (20, 13)], [(13, 38), (15, 29), (38, 38), (30, 10), (37, 12), (43, 5)], [(40, 35)], [(29, 13), (36, 20)], [(25, 2), (28, 2), (40, 37), (30, 7), (32, 19)], [(30, 11), (20, 0), (43, 3)], [(35, 17), (41, 19), (40, 32)], [(25, 37)], [(43, 7), (40, 17), (33, 23)], [(31, 23), (9, 38), (23, 9), (25, 1), (16, 27)], [(29, 13), (31, 25), (30, 22), (35, 10), (38, 23)], [(40, 27)], [(42, 29)], [(35, 33), (37, 5)], [(37, 24), (23, 34), (21, 29)], [(14, 19), (36, 8), (27, 9), (28, 7)], [(44, 30)], [(35, 15

<b>Set maximum weights to each vertice, record the maximum & that the vertice

In [19]:
# Recursively 
# Find node Maximum
class DAG:
    def __init__(self,graph):
        self.graph = graph
        self.startnodes = graph.keys()          # List of nodes
        self.allnodes =  set(list(chain.from_iterable([[x for (x,w) in item] for item in graph.values()]))).union(self.startnodes)
        self.NumVertices = len(self.allnodes)
        print('All Nodes: '+ str(self.NumVertices) + ': '+ str(self.allnodes))
        print('Start nodes: '+ str(len(self.startnodes)) + ': '+ str(list(self.startnodes)))

# Recursive backtracking     
    def DAGPath_sortutil(self, current_node, visited, path):
        visited[current_node] = True
        if current_node in self.startnodes: 
            for next_node, weight in self.graph[current_node]: 
                if next_node in self.startnodes:
                    if not visited[next_node]:                     ### If visited[node] == False
                        self.DAGPath_sortutil(next_node,visited,path)
                else:
                    path.append(current_node)
        path.append(current_node)
             
# Find longest path
    def DAGPath(self, start, end):
        visited = dict.fromkeys(self.startnodes, False)        # Boolean for nodes : visited/ not visited
        path = [] 
        ### Fault-proof
        if start not in self.graph.keys():
            print('Error: No start node!')
            return None
        if start==end:
            return 0, start
        
        for i in self.startnodes: 
            if visited[i] == False: 
                self.DAGPath_sortutil(start, visited, path)
        #print(path)
        dist = dict.fromkeys(self.allnodes, 0);
        while path:  
            i = path.pop(); 
            for next_node,weight in self.graph[i]: 
                if  dist[i] + weight >  dist[next_node]: 
                    dist[next_node] = dist[i] + weight
                    #print('new weights: ' + str(dist))
        for i in self.allnodes: 
            print('node: ' + str(i),'weight: '+ str(dist[i])) if dist[i] != 0 else 0
        return dist[end],
    
    def pathPrinter(path_list):
        text = ''
        for i in path_list[:-1]:
            text += str(i) + '->'
        return text+path_list[-1]

In [20]:
g = DAG(graph);
g.DAGPath(0,44)

All Nodes: 44: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44}
Start nodes: 33: [6, 10, 26, 3, 15, 22, 1, 5, 8, 19, 12, 39, 27, 24, 4, 13, 23, 31, 2, 14, 30, 28, 21, 20, 0, 29, 33, 37, 17, 32, 11, 7, 16]
node: 14 weight: 19
node: 27 weight: 9
node: 28 weight: 7
node: 29 weight: 32
node: 30 weight: 41
node: 31 weight: 44
node: 33 weight: 67
node: 35 weight: 82
node: 36 weight: 29
node: 37 weight: 89
node: 38 weight: 106
node: 40 weight: 68
node: 42 weight: 36
node: 43 weight: 51
node: 44 weight: 62


(62,)