<b>Recursive Changes

In [40]:
%%html
<img src="img/recursive-calls.png",width = 400, height = 400>

In [40]:
import math as m
def RecursiveChanges(money, coins):     #money: single value   #coins: array of denominator values available
    if money == 0 :
        return 0
    minimum_number_coins = m.inf
    count = 0;
    for coin in coins:                 #for each coin in [coin1, coin2, coin3...]
        if coin <= money:
            Number_of_coins = RecursiveChanges(money-coin, coins)
        if Number_of_coins < minimum_number_coins:
            minimum_number_coins = Number_of_coins + 1
    return minimum_number_coins

In [41]:
RecursiveChanges(17,[1,4,5])

4

In [42]:
## Generate an array for m = 1 - 12
max_money = 22; minimum_coins = []; coins = [1,4,5]
for money in range(13,max_money+1):
    minimum_coins.append(RecursiveChanges(money,coins))
print(' '.join(str(i) for i in minimum_coins))

3 3 3 4 4 4 4 4 5 5


<b>Dynamic Programming 

In [75]:
import math as m
def DP_Changes(money,coins):        #money: single value   #coins: array of denominator values available
    minimum_coins = []
    minimum_coins.insert(0,0)
    for mon in range(money):
        minimum_coins.append(m.inf)
        for coin in coins:
            if mon >= coin:           # don't bother if the coin value is larger than money (you cannot get integer)
                last_minimum_coin = minimum_coins[mon-coin]    # recall previous minimum coin for (m-coin)
                if last_minimum_coin + 1 < minimum_coins[mon]:
                    minimum_coins[mon] = last_minimum_coin + 1
    return minimum_coins[mon]

In [72]:
file = open('CC1-change_problem.txt','r')
data = file.read(); data
money, coins, _ = data.split('\n'); money = int(money); coins = [int(i) for i in coins.split(',')]
print(money); print(coins)
file.close()

19281
[6, 5, 3, 1]


In [73]:
minimum_coin_array = DP_Changes(money, coins)
print(minimum_coin_array)

3214


<b>Manhattan Tourist Problem

In [196]:
import numpy as np
def ManhattanTourist(row, col, down_matrix, right_matrix,diag_matrix): #If 4x4 grid | down matrix: 4x5 | right matrix: 5 x 4
    node_matrix = np.zeros((row+1,col+1))    
    for i in range(0,row):   # calculate first column #row: 4 #reiterate 4 times
        node_matrix[i+1][0] = node_matrix[i][0] + down_matrix[i][0]    #down_matrix 4x5
    for j in range(0, col):  # calculate first column #col: 4 #reiterate 4 times
        node_matrix[0][j+1] = node_matrix[0][j] + right_matrix[0][j]   #right_matrix 5x4
    
    for i in range(1,row+1):   # Start calculating (1,1),(1,2)....(1,5)
        for j in range(1,col+1):
            node2node_down = node_matrix[i-1][j] + down_matrix[i-1][j]; 
            node2node_right = node_matrix[i][j-1] + right_matrix[i][j-1];
            node_matrix[i][j] = max(node2node_down,node2node_right)      #get max node value
            if diag_matrix != '':    ## diagonal option
                node_matrix[i][j] = max(node_matrix[i][j],node_matrix[i-1][j-1]+ diag_matrix[i-1][j-1])
            #print(node_matrix)
    return node_matrix[-1][-1]

In [11]:
file = open('CC2-Manhattan_tourist.txt','r')
data = file.read(); data = data.split('\n')
row, col = data[0].split(' '); row = int(row); col = int(col); 
down_matrix_data = data[1:row+1]; down_matrix_data =  [i.split(' ') for i in down_matrix_data]
right_matrix_data = data[row+2:-1]; right_matrix_data = [i.split(' ') for i in right_matrix_data]
file.close()
print(row); print(col);

5
14


In [198]:
down_matrix = np.array([[int(item) for item  in row] for row in down_matrix_data])
right_matrix = np.array([[int(item) for item in row] for row in right_matrix_data])
print(down_matrix); 

[[4 1 4 3 1 4 0 1 2 4 3 0 0 3 3]
 [3 4 4 4 0 1 2 1 0 2 1 1 1 0 1]
 [3 1 2 1 1 4 3 1 0 0 3 1 4 3 1]
 [4 3 1 2 2 3 1 1 4 3 0 3 2 1 3]
 [0 0 2 4 1 4 4 0 4 2 2 0 1 0 1]]


In [199]:
ManhattanTourist(row,col, down_matrix, right_matrix,_)

52.0

<b>Matrix Backtracking

In [227]:
# Denote "down", "right","diagonal" (match) = -1, 0, 1     Dummy Variables
def LCS_Backtrack(string1, string2): #If 4x4 grid       string1: vertical    string2: horizontal
    k1 = len(string1); k2 = len(string2);
    node_matrix = np.zeros((k1+1 ,k2+1))    # assigned a 2D zero matrix for node value 5x5  
    backtrack_matrix = np.zeros((k1,k2))      # backtrack pointers
    for i in range(1,k1+1):   # Start calculating (1,1),(1,2)....(1,5)
        for j in range(1,k2+1):
#Form Node Matrix with Max Value
            if string1[i-1] == string2[j-1]:
                match = 1
            else:
                match = 0
            node_matrix[i][j] = max(node_matrix[i-1][j],node_matrix[i][j-1], node_matrix[i-1][j-1] + match)
# Get pointer from value comparison
            if node_matrix[i][j] == node_matrix[i-1][j]:      #Go DOWN
                backtrack_matrix[i-1][j-1] = -1
            elif node_matrix[i][j] == node_matrix[i][j-1]:    #Go LEFT
                backtrack_matrix[i-1][j-1] = 0            
            elif node_matrix[i][j] == node_matrix[i-1][j-1] + 1  :  #Go Diagonal
                backtrack_matrix[i-1][j-1] = 1
    print('node matrix\n' + str(node_matrix))
    return backtrack_matrix

In [228]:
backtrack_matrix = LCS_Backtrack('AACCTTGG','ACACTG'); 
backtrack_matrix

node matrix
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3. 3.]
 [0. 1. 2. 2. 3. 3. 3.]
 [0. 1. 2. 2. 3. 4. 4.]
 [0. 1. 2. 2. 3. 4. 4.]
 [0. 1. 2. 2. 3. 4. 5.]
 [0. 1. 2. 2. 3. 4. 5.]]


array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1.,  1.,  0.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1.,  1.,  0.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.,  1.],
       [-1., -1., -1., -1., -1., -1.]])

In [747]:
## Uses While Loop
def LCS_1(v,w):
    backtrack_matrix = LCS_Backtrack(v,w); print('Backtrack Matrix: \n'+str(backtrack_matrix))
    i = len(v)-1; j = len(w)-1; string1 = ''; string2 = ''; LCS_array = []
    while i >= 0 or j >= 0:
        '''
        print('(i,j)= ('+ str(i)+ ', ' + str(j)+')' )
        print('Pointer: ' + str(backtrack_matrix[i][j]))
        ''' 
        if backtrack_matrix[i][j] == -1:  ## Down Pointer, go Up
            i = i - 1
            #string2 = '-' + string2; string1 = v[i+1] + string1
        elif backtrack_matrix[i][j] == 0 :    ## Right pointer, go LEFT
            j = j - 1
            #string1 = '-' + string1; string2 = w[j+1] + string2
        elif backtrack_matrix[i][j] == 1:    ## Down pointer, go UP
            #string1 = v[i+1] + string1; string2 = w[i+1] + string2
            LCS_array.insert(0,v[i])
            i = i - 1; j = j - 1;
    return ''.join(LCS_array)    #string1, string2

## Recursive form
def LCS_2(backtrack_matrix, v, i, j):     # i = len(i); j = len(j)
    if i==0 or j==0:
        return
    backtrack_matrix = LCS_Backtrack(v,w); #print(backtrack_matrix)
    if backtrack_matrix[i][j] == -1:    # Down pointer, go up
        LCS_2(backtrack_matrix, v, i-1, j)
    elif backtrack_matrix[i][j] == 0:    # Right pointer, go left
        LCS_2(backtrack_matrix, v, i, j-1)
    else :    #backtrack_matrix[i][j] == 1
        LCS_2(backtrack_matrix, v, i-1, j-1)
        print(v[i])

In [748]:
v = 'AACCTTGG'; w = 'ACACTGTGA'
LCS_1(v,w)

node matrix
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 4. 4. 4. 4. 4.]
 [0. 1. 2. 2. 3. 4. 4. 5. 5. 5.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]]
Backtrack Matrix: 
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.  0.  0.  0.  0.]
 [-1.  1. -1.  1.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  1.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  1.  0.  0.]
 [-1. -1. -1. -1. -1.  1. -1.  1.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]]


'AACTTG'

In [752]:
file = open('CC3-longest_common_subsequence.txt','r')
data = file.read(); data = data.split('\n'); file.close()
v,w,_ = data; #print(v); print(w)

In [751]:
LCS = LCS_1(v,w)
path_length = len(LCS); print(LCS); print(path_length)

node matrix
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   1.   1. ...   1.   1.   1.]
 [  0.   1.   1. ...   2.   2.   2.]
 ...
 [  0.   1.   2. ... 569. 570. 571.]
 [  0.   1.   2. ... 569. 570. 571.]
 [  0.   1.   2. ... 569. 570. 571.]]
Backtrack Matrix: 
[[ 1.  0.  0. ...  0.  0.  0.]
 [-1. -1. -1. ...  0.  0.  0.]
 [-1. -1. -1. ...  0.  0.  0.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]
TCCTTCCTCTAGGCATGGGCTGCCGCTCCCGACTCCGGGGTGTAGGATAACATGTACTGTGTCCAAGCACGGCACTTCTGAGCCAGCTCTGTGCTTCGCCCATCAGAAATGCTCAGGCCAGTCCAGTCTCCGGAGAAATGCGACGTGGGGCACTGCCCGAGGACCAGAGCTGCTGCCCCCCGTGGGTAGGTAGATACCCGTTATTCGTTCGGTCAGCACATTTAAGACGTGAGAAACCCAGAGCGAGGAGTGATACATTGCCCGCAAAATTTACAAAAGCTTCCCCCCAACTGCACGGAGCGTGACCCGACCAGTACAGTAGAAGGAAGTTAAGAGCGTGAGCTTCGCAGGTTAGCTTTGCAGCCGCGCAAAATTGATGGGCAGGTTGTACATCGACGCGGGTATAGATTTTCTCCGCTGGTGGCCATTTCGGTTTACGCCCTCGCATTACGACTAAATAGCTAAGCCGCTGTGAGGGTTTTTTCCAATAAGTTACTTAAGAATTTCGGGCTTGTATGCCGAATCTTGGCGCCGCGATTGCATTCAGGG

<b> Longest Path In DAG

In [81]:
import numpy as np, math as m
file = open('CC4-longest_path_in_DAG.txt','r')
data = file.read(); data = data.split('\n'); 
start, end, node_weights = data[0], data[1], data[2:-1]; file.close(); start = start; end = end
print(node_weights); print(start); print(end)
## Turn data into start points, end point, weights
node_weights = [node_weight.split(':') for node_weight in node_weights]; 
nodes_ = [x.split('->') for x,y in node_weights]; weight_array = [int(y) for x,y in node_weights]; 
start_array = [start for start,end in nodes_]; end_array = [end for start,end in nodes_];

['a->b:3', 'a->c:6', 'a->d:5', 'b->c:2', 'b->f:4', 'c->e:4', 'c->f:3', 'c->g:7', 'd->e:4', 'd->f:5', 'e->g:2']
a
b


In [154]:
from collections import defaultdict
from itertools import chain
def Node2Dict(start_array, end_array, weight_array):     # turn information into dictionary with all information 
    graph = defaultdict(list)
    for start, end, weight in zip(start_array,end_array, weight_array):
        graph[start].append((end,weight))
    return graph

In [155]:
graph = Node2Dict(start_array, end_array, weight_array)
print(graph.keys()); print(graph.values())

dict_keys(['a', 'b', 'c', 'd', 'e'])
dict_values([[('b', 3), ('c', 6), ('d', 5)], [('c', 2), ('f', 4)], [('e', 4), ('f', 3), ('g', 7)], [('e', 4), ('f', 5)], [('g', 2)]])


<b>Set maximum weights to each vertice, record the maximum & that the vertice

In [225]:
# Recursively 
# Find node Maximum
class DAG:
    def __init__(self,graph):
        self.graph = graph
        self.startnodes = graph.keys()          # List of nodes
        self.allnodes =  set(list(chain.from_iterable([[x for (x,w) in item] for item in graph.values()]))).union(self.startnodes)
        self.NumVertices = len(self.allnodes)
        print('All Nodes: '+ str(self.NumVertices) + ': '+ str(self.allnodes))
        print('Start nodes: '+ str(len(self.startnodes)) + ': '+ str(list(self.startnodes)))
# Recursive backtracking     
    def DAGPath_sortutil(self, current_node, visited, path):
        visited[current_node] = True
        if current_node in self.startnodes: 
            for next_node, weight in self.graph[current_node]: 
                if next_node in self.startnodes:
                    if not visited[next_node]:                     ### If visited[node] == False
                        self.DAGPath_sortutil(next_node,visited,path)
        path.append(current_node)          
# Find longest path
    def DAGPath(self, start, end):
        visited = dict.fromkeys(self.startnodes, False)        # Boolean for nodes : visited/ not visited
        path = [] 
        ### Fault-proof
        if start not in self.graph.keys():
            print('Weird...No start node!')
            return None
        if start==end:
            return 0, start
        for i in self.startnodes: 
            if visited[i] == False: 
                self.DAGPath_sortutil(start, visited, path)
        dist = dict.fromkeys(self.allnodes, 0);
        while path:
            i = path.pop(); 
            for next_node,weight in self.graph[i]: 
                if  dist[i] + weight >  dist[next_node]: 
                    print('node: ' + str(i), 'next_node: ' + str(next_node),'end weight:'+ str(dist[i]+weight)) if dist[i] != 0 else 0
                    dist[next_node] = dist[i] + weight
        return dist[end], 
    
    def pathPrinter(path_list):
        text = ''
        for i in path_list[:-1]:
            text += str(i) + '->'
        return text+path_list[-1]

In [226]:
g = DAG(graph); print(start); print(end)
g.DAGPath(start,'g')

All Nodes: 7: {'b', 'f', 'e', 'a', 'c', 'g', 'd'}
Start nodes: 5: ['a', 'b', 'c', 'd', 'e']
a
b
node: d next_node: e end weight:9
node: d next_node: f end weight:10
node: c next_node: e end weight:10
node: c next_node: g end weight:13


(13,)

In [219]:
# Recursively 
# Find node Maximum
class DAG:
    def __init__(self,graph):
        self.graph = graph
        self.startnodes = graph.keys()          # List of nodes
        self.allnodes =  set(list(chain.from_iterable([[x for (x,w) in item] for item in graph.values()]))).union(self.startnodes)
        self.NumVertices = len(self.allnodes)
        print('All Nodes: '+ str(self.NumVertices) + ' nodes : '+ str(self.allnodes))
        print('Start nodes: '+ str(len(self.startnodes)) + ' nodes: '+ str(list(self.startnodes)))

    def DAGLongestPath(self, start, end, path =[]):
        path = path + [start]
        if start == end:
            return [path]
        if start not in self.startnodes:
            return []
        optimal_path = []; all_paths = []; path_weight = 0;
        for (node,weight) in self.graph[start]:
            if node not in path:
                newpaths = self.find_all_paths(node, end, path)
                for newpath in newpaths:
                    all_paths.append(newpath)
                    old_weight = self.PathSum(all_paths[-1])
                    new_weight = self.PathSum(newpath)
                    if new_weight > path_weight:
                        optimal_path.append(newpath)
                        path_weight = new_weight
        return path_weight, optimal_path[-1], all_paths
    
    def find_all_paths(self, start, end, path =[]):
        path = path + [start]
        if start == end:
            return [path]
        if start not in self.startnodes:
            return []
        paths = []
        for (node,weight) in self.graph[start]:
            if node not in path:
                newpaths = self.find_all_paths(node, end, path)
                for newpath in newpaths:
                    paths.append(newpath)
        return paths
    
    def PathSum(self,path_list):
        weight = 0; #print('path_list :',path_list)
        if path_list == []:
            return 0
        elif isinstance(path_list,int):
            return path_list
        for i in range(len(path_list[:-1])):
            thisweight = [path_weight for (next_node, path_weight) in self.graph[path_list[i]] if next_node == path_list[i+1]][0]
            weight += thisweight
        return weight
    def PathPrinter(self, pathlist):
        text = ''
        return ''.join([text+pathlist[i]+'->' for i in range(len(pathlist)-1)])

In [215]:
a = DAG(graph); 
a.DAGLongestPath('a','g')

All Nodes: 7 nodes : {'b', 'f', 'e', 'a', 'c', 'g', 'd'}
Start nodes: 5 nodes: ['a', 'b', 'c', 'd', 'e']


(13,
 ['a', 'c', 'g'],
 [['a', 'b', 'c', 'e', 'g'],
  ['a', 'b', 'c', 'g'],
  ['a', 'c', 'e', 'g'],
  ['a', 'c', 'g'],
  ['a', 'd', 'e', 'g']])